sudo: required
services:
- docker
env:
  global:
  - BASEIMAGE=registry.opensuse.org/devel/openqa/containers/openqa_dev:latest
  matrix:
  - E2MODE=master
  - E2MODE=ln
  - E2MODE=system2
before_script:
- docker pull $BASEIMAGE
script:
- docker run -v $(pwd):/e2 $BASEIMAGE -c "(cd /e2; useradd $(id -nu) -u $(id -u) || :; sudo -u \#$(id -u) .test/product-test.sh $E2MODE)"
