sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT_AUTHOR_EMAIL=skynet@open.qa
  matrix:
  - E2MODE=master
  - E2MODE=ln
before_script:
- docker pull registry.opensuse.org/devel/openqa/containers/openqa_dev:latest
script:
- docker run --name travis -v $(pwd):/e2 registry.opensuse.org/devel/openqa/containers/openqa_dev:latest -c 'sleep 10000' &
- docker exec travis bash -c "(cd /e2 && sudo -u \#$(id -u) .test/product-test.sh $E2MODE)"
after_script:
- docker exec travis bash -c "cat /e2/.log/RES"
